[package]
name = "cirrus"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.15.0"
itertools = "0.14.0"
lazy_static = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
